POST http://127.0.0.1:8000/user/sign-up
Content-Type: application/json

{
  "email": "adan@grr.la",
  "password": "super_duper_secret_password"
}

###

POST http://127.0.0.1:8000/user/sign-in
Content-Type: application/json

{
  "email": "adan@grr.la",
  "password": "super_duper_secret_password"
}

###
POST http://127.0.0.1:8000/quotes/create
Content-Type: application/json

{
  "Name": "Adan Eva",
  "Email": "adan@grr.la",
  "NumberPhone": "3196569548",
  "Address": "Street 7 Number 122",
  "Observation": ""
}

###
POST http://127.0.0.1:8000/user/documents/obligatory
Content-Type: application/json

{
  "Process": "a0499fcf-561d-4db8-8947-1ebfadd8a913",
  "Documents": [{
    "Type": "RUT",
    "MIME": "pdf",
    "Base64": "{{FileDummyPDF}}"
  }, {
    "Type": "Identification",
    "MIME": "pdf",
    "Base64": "{{FileDummyPDF}}"
  },  {
    "Type": "Certificate",
    "MIME": "pdf",
    "Base64": "{{FileDummyPDF}}"
  }]
}

###
GET http://127.0.0.1:8000/operator/review/documents/pending